#!/bin/bash
#
# Export a list of CouchDB databases from the server to JSON files.
# Then bundle the exported files.
# copy folders from etc, lib, log and zip

backup_path="/tmp/couchdb_backup/"
mkdir -p $backup_path

filename="/tmp/couchdb_backup/couchdb_backup"
current_date=$(date "+%Y-%m-%d")

new_filename=$filename"_"$current_date
#mkdir $new_filename
seven_days_back=$(date -d "-7 days" +%Y-%m-%d)
rm -rf $filename"_"$seven_days_back

#echo $new_filename
cp -r /opt/couchdb/data $new_filename